SET NUMERIC_ROUNDABORT OFF
GO
SET XACT_ABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
GO
-- Permissions 
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (1, N'CLOSE_ISSUE', N'Close Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (2, N'ADD_ISSUE', N'Add Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (3, N'ASSIGN_ISSUE', N'Assign Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (4, N'EDIT_ISSUE', N'Edit Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (5, N'SUBSCRIBE_ISSUE', N'Subscribe Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (6, N'DELETE_ISSUE', N'Delete Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (7, N'ADD_COMMENT', N'Add Comment')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (8, N'EDIT_COMMENT', N'Edit Comment')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (9, N'DELETE_COMMENT', N'Delete Comment')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (10, N'ADD_ATTACHMENT', N'Add Attachment')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (11, N'DELETE_ATTACHMENT', N'Delete Attachment')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (12, N'ADD_RELATED', N'Add Related Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (13, N'DELETE_RELATED', N'Delete Related Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (14, N'REOPEN_ISSUE', N'Re-Open Issue')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (15, N'OWNER_EDIT_COMMENT', N'Edit Own Comments')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (16, N'EDIT_ISSUE_DESCRIPTION', N'Edit Issue Description')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (17, N'EDIT_ISSUE_TITLE', N'Edit Issue Title')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (18, N'ADMIN_EDIT_PROJECT', N'Admin Edit Project')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (19, N'ADD_TIME_ENTRY', N'Add Time Entry')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (20, N'DELETE_TIME_ENTRY', N'Delete Time Entry')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (21, N'ADMIN_CREATE_PROJECT', N'Admin Create Project')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (22, N'ADD_QUERY', N'Add Query')
INSERT INTO [BugNet_Permissions] ([PermissionId], [PermissionKey], [PermissionName]) VALUES (23, N'DELETE_QUERY', N'Delete Query')

-- Host Settings 
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'AdminNotificationUsername', N'admin')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'ADPassword', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'ADPath', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'ADUserName', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'AllowedFileExtensions', N'*.*')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'ApplicationTitle', N'BugNET Issue Tracker')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'DefaultUrl', N'http://localhost/BugNet/')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'DisableAnonymousAccess', N'False')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'DisableUserRegistration', N'False')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'EmailErrors', N'False')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'EnabledNotificationTypes', N'Email;MSN')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'EnableRepositoryCreation', N'True')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'ErrorLoggingEmailAddress', N'myemail@mysmtpserver.com')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'FileSizeLimit', N'2024')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'HostEmailAddress', N'noreply@mysmtpserver.com')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3BodyTemplate', N'&lt;div &gt;Sent by:{1} on: {2}&lt;br&gt;{0}&lt;/div&gt;')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3DeleteAllMessages', N'False')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3InlineAttachedPictures', N'False')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3Interval', N'6000')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3Password', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3ReaderEnabled', N'True')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3ReportingUsername', N'Admin')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3Server', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Pop3Username', N'bugnetuser')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'RepositoryBackupPath', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'RepositoryRootPath', N'C:\SVN\')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'RepositoryRootUrl', N'svn://localhost/')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SMTPAuthentication', N'False')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SMTPPassword', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SMTPPort', N'25')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SMTPServer', N'localhost')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SMTPUsername', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SMTPUseSSL', N'False')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SvnAdminEmailAddress', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'SvnHookPath', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'UserAccountSource', N'None')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'Version', N'')
INSERT INTO [BugNet_HostSettings] ([SettingName], [SettingValue]) VALUES (N'WelcomeMessage', N'Welcome to your new BugNET installation! Log in as <br/><br/> Username: admin <br/>Password: password')

-- Custom Field Types 
INSERT INTO [BugNet_ProjectCustomFieldTypes] ([CustomFieldTypeName]) VALUES (N'Text')
INSERT INTO [BugNet_ProjectCustomFieldTypes] ([CustomFieldTypeName]) VALUES (N'Drop Down List')
INSERT INTO [BugNet_ProjectCustomFieldTypes] ([CustomFieldTypeName]) VALUES (N'Date')
INSERT INTO [BugNet_ProjectCustomFieldTypes] ([CustomFieldTypeName]) VALUES (N'Rich Text')
INSERT INTO [BugNet_ProjectCustomFieldTypes] ([CustomFieldTypeName]) VALUES (N'Yes / No')
INSERT INTO [BugNet_ProjectCustomFieldTypes] ([CustomFieldTypeName]) VALUES (N'User List')

-- Required Field List
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'-- Select Field --', N'0')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Issue ID', N'IssueID')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Title', N'IssueTitle')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Category', N'IssueCategoryId')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Priority', N'IssuePriorityId')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Milestone', N'IssueMilestoneId')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Status', N'IssueStatusId')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Assigned', N'IssueAssignedId')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Owner', N'IssueOwnerId')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Creator', N'IssueCreatorId')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Date Created', N'DateCreated')
INSERT INTO [BugNet_RequiredFieldList] ([FieldName], [FieldValue]) VALUES (N'Custom Fields', N'CustomFieldName')

-- Roles and Permissions 
PRINT 'Add Default Roles & Permissions'
EXEC BugNet_Role_CreateNewRole @ProjectId = NULL, @RoleName = 'Super Users', @RoleDescription = 'A role for project super users', @AutoAssign = 0

-- String Resources
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'AssgnedTo', N'Assigned To')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Assigned', N'Assigned')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Cancel', N'Cancel')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Category', N'Category')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'ChangePassword', N'Change Password')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'ConfirmPassword', N'Confirm Password:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'ConfirmPasswordErrorMessage', N'The passsword and confirmation password must match.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Created', N'Created')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Creator', N'Creator')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Delete', N'Delete')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Description', N'Description')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'DisplayName', N'Display Name:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'DueDate', N'Due Date')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Edit', N'Edit')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Email', N'Email:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Estimation', N'Estimation')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms ', N'en ', N'EstimationHours', N'Estimation (hrs)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'FirstName', N'First Name:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Id', N'Id')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'IssueHeader', N'Issue (click title to view details)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'IssueId', N'Issue Id:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'LastName', N'Last Name:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'LastUpdate', N'Last Update')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'LastUpdateUser', N'Last Update User')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Milestone', N'Milestone')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'NoIssueResults', N'There are no issues that match your criteria.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Of', N'of')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Owner', N'Owner')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Page', N'Page')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Password', N'Password:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Priority', N'Priority')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Private', N'Private')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Progress', N'Progress')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Required', N'(required)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Resolution', N'Resolution')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Return', N'Return')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Save', N'Save')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Status', N'Status')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Submit', N'Submit')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'TimeLogged', N'Time Logged')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'TimeLoggedHours', N'Time Logged (hrs)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Title', N'Title')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Type', N'Type')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'Username', N'Username:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'CommonTerms', N'en', N'UsernameRequired.ErrorMessage', N'Username is required.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'LoginControl.CreateUserText', N'Register')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'LoginControl.FailureText', N'Your login attempt was not successful. Please try again.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'LoginControl.LoginButtonText', N'Log in')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'LoginControl.PasswordRecoveryText', N'Forgot your password?')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'LoginControl.RememberMeText', N'Remember me next time.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'LoginControl.Text', N'Log In')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'LoginControl.TitleText', N'Login')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'en', N'Page.Title', N'Home')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Default.aspx', N'fr-FR', N'Page.Title', N'This is testing the localization features ')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ErrorMessages', N'en', N'InvalidFileType', N'{0} does not meet the allowed file types.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ErrorMessages', N'en', N'UploadPathNotDefined', N'Project upload path has not been defined for project {0}.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ErrorMessages', N'en ', N'UploadPathNotFound', N'Upload directory {0} can not be found. Please check with the administrator that the directory exists on the web server.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'CapchaTest.ControlMessage', N'Enter the code you see:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'CodeIncorrectError', N'The code you entered was incorrect.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'EmailPasswordReminderError', N'An error occured sending the password reminder.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'lblInstructions.Text', N'Enter your username to receive your password.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'lblTitle.Text', N'Forgot Your Password?')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'Page.Title', N'Forgot Password')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'PasswordReminderSuccess', N'Your password has been emailed to you successfully.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'ForgotPassword.aspx', N'en', N'UserNotFoundError', N'The user you entered was not found.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'btnAdd.Text', N'Create New Issue')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'InLabel.Text', N'in')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'ListItem1.Text', N'Relevant to You')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'ListItem2.Text', N'Assigned to You')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'ListItem3.Text', N'Owned by You')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'ListItem4.Text', N'Created by You')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'ListItem5.Text', N'All Issues')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'Page.Title', N'Issue List')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'IssueList.aspx', N'en', N'ViewIssuesLabel.Text', N'View Issues')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'AssignedToLabel.Text', N'Assigned To:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'ByLabel.Text', N'By:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'CategoryLabel.Text', N'Category:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'DateCreatedLabel.Text', N'Date Created:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'DeleteIssue', N'Are you sure you want to delete this issue?')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'DetailsLabel.Text', N'Details')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'DueDateLabel.Text', N'Due Date:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'EstimationLabel.Text', N'Estimation:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'HoursLabel.Text', N'hrs')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'IssueLabel.Text', N'Issue:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'IssueTypeLabel.Text', N'Type:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'LastUpdateLabel.Text', N'Last Update:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'LoggedLabel.Text', N'Logged:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'MilestoneLabel.Text', N'Milestone:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'OwnedByLabel.Text', N'Owned By:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'PageTitleNewIssue', N'New Issue')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'PriorityLabel.Text', N'Priority:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'PrivateLabel.Text', N'Private:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'ResolutionLabel.Text', N'Resolution:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'SaveReturn.Text', N'Save &amp; Return')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'StatusLabel.Text', N'Status:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'TimeLabel.Text', N'Time')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/IssueDetail.aspx', N'en', N'TitleLabel.Text', N'Title:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'AttachmentsGrid.Description.Text', N'Description')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'AttachmentsGrid.FileNameHeader.Text', N'File Name')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'AttachmentsGrid.SizeHeader.Text', N'Size')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'CancelUploads', N'Cancel Uploads')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'DeleteAttachment', N'Are you sure you want to delete this attachment?')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'lblAddAttachment.Text', N'Add Attachment')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'NoAttachments', N'There are no attachments for this issue.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Attachments.ascx', N'en', N'SelectFiles', N'Select files')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Comments.ascx', N'en', N'cmdAddComment.Text', N'Add Comment')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Comments.ascx', N'en', N'cmdEditComment.Text', N'Edit Comment')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Comments.ascx', N'en', N'DeleteComment', N'Are you sure you want to delete this comment?')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Comments.ascx', N'en', N'hlPermalink.Text', N'Permalink')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Comments.ascx', N'en', N'Image1.AlternateText', N'User comment')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Comments.ascx', N'en', N'LeaveComment.Text', N'Leave a comment')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Comments.ascx', N'en', N'NoComments', N'There are no comments for this issue.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/History.ascx', N'en', N'HistoryDataGrid.CreatorHeader.Text', N'User')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/History.ascx', N'en', N'HistoryDataGrid.DateModifiedHeader.Text', N'Date Modified')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/History.ascx', N'en', N'HistoryDataGrid.FieldChangedHeader.Text', N'Item Changed')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/History.ascx', N'en', N'HistoryDataGrid.NewValueHeader.Text', N'New Value')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/History.ascx', N'en', N'HistoryDataGrid.OldValueHeader.Text', N'Previous Value')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/History.ascx', N'en', N'NoHistory', N'This issue has not been modified.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Notifications.ascx', N'en', N'btnAddNot.Text', N'Add >>')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Notifications.ascx', N'en', N'btnDelNot', N'<< Remove')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Notifications.ascx', N'en', N'btnDontRecieveNotfictaions.Text', N'Don''t Receive Notifications')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Notifications.ascx', N'en', N'btnReceiveNotifications.Text', N'Receive Notifications')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Notifications.ascx', N'en', N'lblDescription.Text', N'The following person(s) receive email notifications when this issue is updated:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Notifications.ascx', N'en', N'pnlNotificationAdmin.GroupingText', N'Add Remove Notifications(Managers Only)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/ParentIssues.ascx', N'en', N'btnAdd.Text', N'Add Parent Issue')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/ParentIssues.ascx', N'en', N'CompareValidator1.Text', N'(integer)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/ParentIssues.ascx', N'en', N'lblDescription.Text', N'List all issues on which this issue depends. Enter the ID of the issue in the text box below and click the Add Parent Issue button.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/RelatedIssues.ascx', N'en', N'CompareValidator1.Text', N'(integer)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/RelatedIssues.ascx', N'en', N'lblAddRelatedIssue.Text', N'Add Related Issue')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/RelatedIssues.ascx', N'en', N'lblDescription.Text', N'List all issues on which this issue is related. Enter the ID of the issue in the text box below and click the Add Related Issue button.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/RelatedIssues.ascx', N'en', N'NoRelatedIssues', N'There are no related issues.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Revisions.ascx', N'en', N'IssueRevisionsDataGrid.AuthorHeader.Text', N'Author')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Revisions.ascx', N'en', N'IssueRevisionsDataGrid.MessageHeader.Text', N'Message')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Revisions.ascx', N'en', N'IssueRevisionsDataGrid.RepositoryHeader.Text', N'Repository')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Revisions.ascx', N'en', N'IssueRevisionsDataGrid.RevisionDateHeader.Text', N'Revision Date')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Revisions.ascx', N'en', N'IssueRevisionsDataGrid.RevisionHeader.Text', N'Revision')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/Revisions.ascx', N'en', N'NoRevisions', N'There are no revisions linked to this issue.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/SubIssues.ascx', N'en', N'btnAdd.Text', N'Add Sub Issue')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/SubIssues.ascx', N'en', N'CompareValidator1.Text', N'(integer)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/SubIssues.ascx', N'en', N'lblDescription.Text', N'List all Issues that are dependent on the current issue. Enter the ID of the issue in the text box below and click the Add Sub Issue button.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'AddTimeEntry.Text', N'Add Time Entry')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'cmdAddTimeEntry.Text', N'Add Time Entry')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'CommentOptional', N'(optional - will be added as an issue comment)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'Comments.Text', N'Comments:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'compDateDataTypeValidator.ErrorMessage', N'You must enter a valid date.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'cpTimeEntry.ErrorMessage', N'Date cannot be in the future.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'DateLabel.Text', N'Date:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'DeleteTimeEntry', N'Are you sure you wish to delete this entry?')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'lblDuration.Text', N'Duration:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'NoTimeEntries', N'There are no time tracking reports for this issue.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'RangeValidator1.ErrorMessage', N'Duration is out of range.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'TimeEntriesDataGrid.CommentHeader.Text', N'Comment')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'TimeEntriesDataGrid.CreatorHeader.Text', N'User')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'TimeEntriesDataGrid.DurationHeader.Text', N'Hours')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Issues/UserControls/TimeTracking.ascx', N'en', N'TimeEntriesDataGrid.WorkDateHeader.Text', N'Date')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'IssueAdded', N'The following issue has been added to a project that you are monitoring.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'IssueAddedSubject', N'Issue {1} has been added to a project you are monitoring.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'IssueUpdated', N'The following issue has been updated: \n\n[DefaultUrl]Issues/IssueDetail.aspx?id=[Issue_Id]\n\nTitle: [Issue_Title]\nProject: [Issue_Project]')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'IssueUpdatedSubject', N'Issue {0} has been updated by {1}')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'IssueUpdatedWithChanges', N'The following issue has been updated: \n\n[DefaultUrl]Issues/IssueDetail.aspx?id=[Issue_Id]\n{0}')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'NewAssignee', N'The following issue has been assigned to you: \n\n[DefaultUrl]Issues/IssueDetail.aspx?id=[Issue_Id]')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'NewAssigneeSubject', N'Issue {0} has been assigned to you')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'NewIssueComment', N'A new comment has been added to the following issue.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'NewIssueCommentSubject', N'Issue {0} has a new comment')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'PasswordReminder', N'You have requested a password reminder from {0}. Your password is: {1}')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'PasswordReminderSubject', N'Password Reminder')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'UserRegistered', N'Date: [User_DateCreated]\nName: [User_DisplayName]\n Username: [User_Username]\nEmail: [User_Email]')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Notification', N'en', N'UserRegisteredSubject', N'New User Registration')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ChangeLog.aspx', N'en', N'Page.Title', N'Change Log')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ChangeLog.aspx', N'en', N'TitleLabel.Text', N'Change Log')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'btnNext.Text', N'Next >')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'btnNext.ToolTip', N'Next')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'btnPrevious.Text', N'< Previous')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'btnPrevious.ToolTip', N'Previous')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'CalendarViewLabel.Text', N'View:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'ListItem1.Text', N'Month')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'ListItem2.Text', N'Week')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectCalendar.aspx', N'en', N'Page.Title', N'Project Calendar')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'ByAssignee.Text', N'Assignee')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'Categories.Text', N'Categories')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'IssuesByAssignee.Text', N'Issues by assignee')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'IssuesByCategory.Text', N'Issues by category')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'IssuesByMilestone.Text', N'Issues by milestone')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'IssuesByPriority.Text', N'Issues by priority')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'IssuesByStatus.Text', N'Issues by status')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'IssuesByType.Text', N'Issues by type')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'MilestonesLabel.Text', N'Milestones')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'OpenIssues.Text', N'(open issues)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/ProjectSummary.aspx', N'en', N'Page.Title', N'Project Summary')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/RoadMap.aspx', N'en', N'Page.Title', N'Roadmap')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/RoadMap.aspx', N'en', N'ProgressMessage', N'{2}% complete<br/>{0} of {1} issues have been resolved')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Projects/RoadMap.aspx', N'en', N'TitleLabel.Text', N'Roadmap')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'btnAddClause.Text', N'Add Clause')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'btnPerformQuery.Text', N'Perform Query')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'btnRemoveClause.Text', N'Remove Clause')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'btnSaveQuery.Text', N'Save Query')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'chkGlobalQuery.Text', N'All all users to run this query')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'lblProject.Text', N'Project:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'Page.Title', N'Query Detail')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'RunQueryError', N'Error in query. Please check query values.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryDetail.aspx', N'en', N'SaveQueryError', N'Could not save query.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryList.aspx', N'en', N'btnAddQuery.Text', N'Add Query')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryList.aspx', N'en', N'btnDeleteQuery.Text', N'Delete Query')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryList.aspx', N'en', N'btnPerformQuery.Text', N'Perform Query')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryList.aspx', N'en', N'lblProject.Text', N'Project:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryList.aspx', N'en', N'Page.Title', N'Query List')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryList.aspx', N'en', N'QueryError', N'Error in query. Please check query values.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Queries/QueryList.aspx', N'en', N'Results.Text', N'Results:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'ConfirmPasswordLabel.Text', N'Please enter your details and confirm your password to register an account.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'EmailLabel.Text', N'Email:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'EmailRequired.ErrorMessage', N'Email is required.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'FirstNameRequired.ErrorMessage', N'First name is required.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'FullNameLabel.Text', N'Display Name:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'FullNameRequired.ErrorMessage', N'Display name is required.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'InstructionsLabel.Text', N'Please enter your details and confirm your password to register an account.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'LastNameRequired.ErrorMessage', N'Last name is required.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'Page.Title', N'Register')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'PasswordCompare.ErrorMessage', N'The Password and Confirmation Password must match.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'PasswordRequired.ErrorMessage', N'Password is required.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'Register.aspx', N'en', N'TitleLabel.Text', N'Sign up for your new account')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/DisplayIssues.ascx', N'en', N'EditPropertiesLabel.Text', N'Edit Properties')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/DisplayIssues.ascx', N'en', N'imgPrivate.AlternativeText', N'This issue is marked as private')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/DisplayIssues.ascx', N'en', N'lblIssues.Text', N'(Sort the results by clicking the column headings)')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/DisplayIssues.ascx', N'en', N'SelectColumnsLinkButton.Text', N'Add / remove columns')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/DisplayIssues.ascx', N'en', N'SelectColumnsLiteral.Text', N'Select columns:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/DisplayIssues.ascx', N'en', N'SetPropertiesLabel.Text', N'Set properties for selected issues:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickCategory.ascx', N'en', N'SelectCategory', N'-- Select Category --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickMilestone.ascx', N'en', N'SelectMilestone', N'-- Select Milestone --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickPriority.ascx', N'en', N'SelectPriority', N'-- Select Priority --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickProject.ascx', N'en', N'SelectProject', N'-- Select Project --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickQuery.ascx', N'en', N'SelectQuery', N'-- Select Query --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickResolution.ascx', N'en', N'SelectResolution', N'-- Select Resolution --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickSingleUser.ascx', N'en', N'SelectUser', N'-- Select User --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickStatus.ascx', N'en', N'SelectStatus', N'-- Select Status --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/PickType.ascx', N'en', N'SelectType', N'-- Select Type --')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/TabMenu.ascx', N'en', N'Admin', N'Admin')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/TabMenu.ascx', N'en', N'Home', N'Home')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/TabMenu.ascx', N'en', N'Issues', N'Issues')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/TabMenu.ascx', N'en', N'ProjectSummary', N'Project Summary')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/TabMenu.ascx', N'en', N'Queries', N'Queries')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/TabMenu.ascx', N'en', N'Reports', N'Reports')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserControls/TabMenu.ascx', N'en', N'Source', N'Browse Source')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'cbAssigned.Text', N'Assigned to me')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'cbClosed.Text', N'Closed by me')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'cbInProgress.Text', N'In progress by me')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'cbMonitored.Text', N'Monitored by me')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'cbReported.Text', N'Reported by me')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'cbResolved.Text', N'Resolved by me')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'Label111.Text', N'New Password:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'lblItemPageSize.Text', N'Issue Page Size:')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'ProfileSaved', N'Your profile has been updated.')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'ProfileUpdateError', N'An error occrred updating your profile')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'TreeNode1.Text', N'User Details')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'TreeNode2.Text', N'Manage Password')
INSERT INTO [BugNet_StringResources] ([resourceType], [cultureCode], [resourceKey], [resourceValue]) VALUES (N'UserProfile.aspx', N'en', N'TreeNode3.Text', N'Customize')